name: .NET

on:
  push:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c release --no-restore
      
    - name: Package Invoice kit
      run: dotnet pack -c release --no-build -o ./nuget/

    - name: Upload Cli Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: invoice-kit-cli
        path: |
          ./**/*.nupkg
    - name: Publish NuGet
      run: dotnet nuget push ./**/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
